// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_G4b6bJdtTp0I37-F5XfkbqcvoDKVIJs',
    appId: '1:359252449242:android:37ad49dfab6d334662d2e3',
    messagingSenderId: '359252449242',
    projectId: 'piton-pass',
    storageBucket: 'piton-pass.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_An9RhzPhI0n3Sdhxpf5XNsKraIK3Rdc',
    appId: '1:359252449242:ios:630589980f50fdf262d2e3',
    messagingSenderId: '359252449242',
    projectId: 'piton-pass',
    storageBucket: 'piton-pass.firebasestorage.app',
    iosBundleId: 'com.example.mobilTemplate',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUPocedNIE3U8580VbRmUsDY572Rg3Y38',
    appId: '1:359252449242:web:c5dcf1f919befb5862d2e3',
    messagingSenderId: '359252449242',
    projectId: 'piton-pass',
    authDomain: 'piton-pass.firebaseapp.com',
    storageBucket: 'piton-pass.firebasestorage.app',
    measurementId: 'G-MBK1R7P5CT',
  );
}
